### PR TITLE
translation update - fix untranslated string

### PR DESCRIPTION
**Pull request by HerzScheisse**
Hi,

I hope this is the right way and i didnt do anything wrong... 

I've found a untranslated string and first tried to translate it via weblate... but it was not there... so I started to search through some files... in the end I didn't found any occurrences of that string, so i added it...

I cant find the origin of the untranslated version, so i just updated the line number for the "Research Suggestions" plural-version 

Some other edits like formating in this PR is from POEdit... feel free to delete them...

"Research Suggestion" is used in shared places -> history of place

### CODE REVIEW

**Comment by ric2016** [comment]
These files are auto-generated from code and any direct change would be overwritten later.

Anyway, if the source string isn't managed in webtrees (via `I18N::translate`), it won't help to add a translation.

Where does this string "Research Suggestion" show up? Do you have a screenshot?
I only see [this](https://github.com/vesta-webtrees-2-custom-modules/vesta_research_suggestions/blob/dc2a431ce3edc9afbbbd97a025f301aed4451ba9/ResearchSuggestionsService.php#L192), but  apparently that's only used internally.

**Comment by HerzScheisse** [comment]
okay thanks for explaining... in case this PR is useless feel free to delete it and add these modifications in any other prefered way...

yeah i cant find it in any other file too... so i added it and it's now translated...

transl research suggestion
its used in the shared place page under the last tab...

BUT while searching for this again i stumpled upon another untranslated string:
transl gov hierachy

`GOV Hierarchy` should be translated too...


Hope these screenshots help to lacated the problem

**Comment by ric2016** [comment]
Thank you for the screenshots, I forgot about the place history.
I'll add "Research Suggestion" and "GOV Hierarchy" as translatable strings in the respective modules.


> so i added it and it's now translated...

I see - that works by chance in this specific case because [webtrees makes all fact labels 'dynamically' translatable](https://github.com/fisharebest/webtrees/blob/d11b6d871f0ef4a835494c1d71b139bb6dc3209d/app/Fact.php#L471), this is intended to allow users to use their own EVEN types.

**Comment by ric2016** [comment]
The new strings are now available in weblate.

Ich könnte ja Deutsch auch mal selber übersetzen, aber ich halte mich da grundsätzlich raus ;-)
(Ich benutze selber lieber die englische Version von webtrees, deswegen fallen mir solche Stellen regelmäßig auch nicht auf)

**Pull request closed without merging**
